# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll", "~> 4.4.1"
gem "just-the-docs", "~> 0.12.0"
gem "logger"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
